name       : ncdu
version    : 1.14.1
release    : 7
source     :
    - https://dev.yorhel.nl/download/ncdu-1.14.1.tar.gz : be31e0e8c13a0189f2a186936f7e298c6390ebdc573bb4a1330bc1fcbf56e13e
homepage   : http://dev.yorhel.nl/ncdu
license    :
    - MIT
summary    : Disk usage analyzer with ncurses interface
component  : system.utils
description: |
    ncdu is a disk usage analyzer with an ncurses interface, aimed to be run on a remote server over SSH. It is therefore designed to be fast, simple, and easy to use
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
