name       : ncdu
version    : '1.15'
release    : 9
source     :
    - https://dev.yorhel.nl/download/ncdu-1.15.tar.gz : 4a593dc5cceb2492a9669f5f5d69d0e517de457a11036788ea4591f33c5297fb
homepage   : https://dev.yorhel.nl/ncdu
license    : MIT
component  : system.utils
summary    : Disk usage analyzer with ncurses interface
description: |
    ncdu is a disk usage analyzer with an ncurses interface, aimed to be run on a remote server over SSH. It is therefore designed to be fast, simple, and easy to use
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
