name       : ncdu
version    : '1.13'
release    : 6
source     :
    - https://dev.yorhel.nl/download/ncdu-1.13.tar.gz : f4d9285c38292c2de05e444d0ba271cbfe1a705eee37c2b23ea7c448ab37255a
homepage   : http://dev.yorhel.nl/ncdu
license    :
    - MIT
summary    : Disk usage analyzer with ncurses interface
component  : system.utils
description: |
    ncdu is a disk usage analyzer with an ncurses interface, aimed to be run on a remote server over SSH. It is therefore designed to be fast, simple, and easy to use
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
